<?php return 
array(
    'key' => 'zadmin_fields_advanced_backup',
    'label' => 'Backup',
    'name' => 'backup',
    'aria-label' => '',
    'type' => 'group',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '50',
        'class' => '',
        'id' => '',
    ),
    'layout' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'backup_code',
            'label' => 'Backup Code',
            'name' => 'backup_code',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => '',
            'placeholder' => '',
            'new_lines' => '',
        ),
        array(
            'key' => 'field_641592391242a2',
            'label' => 'Click to general new Backup',
            'name' => 'backup_code_btn',
            'aria-label' => '',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'Submit' => 'Submit',
            ),
            'default_value' => '',
            'return_format' => 'value',
            'allow_null' => 0,
            'layout' => 'horizontal',
        ),
    ),
); ?>