<?php return array(
    'key' => 'field_6414b0082ca4d',
    'label' => 'Menu Settings',
    'name' => 'menu_settings',
    'aria-label' => '',
    'type' => 'group',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '100',
        'class' => '',
        'id' => '',
    ),
    'layout' => 'table',
    'sub_fields' => array(
        array(
            'key' => 'field_6414b3230d183',
            'label' => 'Group title',
            'name' => 'group_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_6414b3290d184',
            'label' => 'Default color',
            'name' => 'default_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'enable_opacity' => 0,
            'return_format' => 'string',
        ),
        array(
            'key' => 'field_6414b40600762',
            'label' => 'Hide menu item title on mobile',
            'name' => 'hide_menu_item_title_on_mobile',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        array(
            'key' => 'field_6414b41000763',
            'label' => 'Hide other if style fixed bottom mobile assigned',
            'name' => 'hide_other_if_style_fixed_bottom_mobile_assigned',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
    ),
); ?>