<?php return array(
    'key' => 'field_64173e3574ed3',
    'label' => 'Add to cart',
    'name' => 'add_to_cart',
    'aria-label' => '',
    'type' => 'group',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '50',
        'class' => '',
        'id' => '',
    ),
    'layout' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_6417409540fa0',
            'label' => 'Add to cart text',
            'name' => 'add_to_cart_text',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_641740b140fa1',
            'label' => 'Remove add to cart button',
            'name' => 'remove_add_to_cart_button',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        array(
            'key' => 'field_641740d340fa4',
            'label' => 'Redirect to checkout',
            'name' => 'remove_add_to_cart_button_copy',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        array(
            'key' => 'field_641740d840fa5',
            'label' => 'Ajax in single product',
            'name' => 'remove_add_to_cart_button_copy2',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        array(
            'key' => 'field_641740df40fa6',
            'label' => 'Buy now redirect checkout',
            'name' => 'add_to_cart_text_copy',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_641740f140fa7',
            'label' => 'Buy now position',
            'name' => 'buy_now_position',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'woocommerce_single_product_summary' => 'woocommerce_single_product_summary',
                'woocommerce_before_add_to_cart_form' => 'woocommerce_before_add_to_cart_form',
                'woocommerce_before_variations_form' => 'woocommerce_before_variations_form',
                'woocommerce_before_add_to_cart_button' => 'woocommerce_before_add_to_cart_button',
                'woocommerce_before_single_variation' => 'woocommerce_before_single_variation',
                'woocommerce_single_variation' => 'woocommerce_single_variation',
                'woocommerce_before_add_to_cart_quantity' => 'woocommerce_before_add_to_cart_quantity',
                'woocommerce_after_add_to_cart_quantity' => 'woocommerce_after_add_to_cart_quantity',
                'woocommerce_after_single_variation' => 'woocommerce_after_single_variation',
                'woocommerce_after_add_to_cart_button' => 'woocommerce_after_add_to_cart_button',
                'woocommerce_after_variations_form' => 'woocommerce_after_variations_form',
                'woocommerce_after_add_to_cart_form' => 'woocommerce_after_add_to_cart_form',
                'woocommerce_product_meta_start' => 'woocommerce_product_meta_start',
                'woocommerce_product_meta_end' => 'woocommerce_product_meta_end',
                'woocommerce_share' => 'woocommerce_share',
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6417414340fa8',
            'label' => 'Remove quanity field',
            'name' => 'remove_quanity_field',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
    ),
); ?>