<?php 

// add_filter( 'zadmin_acf_fields', function($fields){
	$data = [
        array(
            'key' => 'field_641591fa12291',
            'label' => 'SMTP Settings',
            'name' => 'smtp_settings',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => 'This plugin copy function from SMTP Mailer',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_6415926866445',
                    'label' => 'Disable this',
                    'name' => 'disable_this',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_6415928266446',
                    'label' => 'Host',
                    'name' => 'host',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'The SMTP server which will be used to send email. For example: smtp.gmail.com',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6415928c66447',
                    'label' => 'Username',
                    'name' => 'username',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'Your SMTP Username.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6415928f66448',
                    'label' => 'Password',
                    'name' => 'username_copy',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'Your SMTP Password (The saved password is not shown for security reasons. You must re-enter the password when saving the information again).',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6415929766449',
                    'label' => 'From',
                    'name' => 'username_copy2',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'The email address which will be used as the From Address if it is not supplied to the mail function.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6415929f6644a',
                    'label' => 'FromName',
                    'name' => 'username_copy3',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'The name which will be used as the From Name if it is not supplied to the mail function.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_641592a66644b',
                    'label' => 'Port',
                    'name' => 'username_copy4',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'The port which will be used when sending an email (587/465/25). If you choose TLS it should be set to 587. For SSL use port 465 instead.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_641592ad6644c',
                    'label' => 'SMTPAuth',
                    'name' => 'username_copy5',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => 'Whether to use SMTP Authentication when sending an email (recommended: True).',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_641592be6644d',
                    'label' => 'SMTPSecure',
                    'name' => 'smtpsecure',
                    'aria-label' => '',
                    'type' => 'radio',
                    'instructions' => 'The encryption which will be used when sending an email (recommended: TLS).',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'tls' => 'tls',
                        'ssl' => 'ssl',
                    ),
                    'default_value' => '',
                    'return_format' => 'value',
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'layout' => 'horizontal',
                    'save_other_choice' => 0,
                ),
                array(
                    'key' => 'field_641592cd6644e',
                    'label' => 'Enable SSL Certificate Verification',
                    'name' => 'enable_ssl_certificate_verification',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => 'As of PHP 5.6 you will get a warning/error if the SSL certificate on the server is not properly configured. You can check this option to disable that default behaviour. Please note that PHP 5.6 made this change for a good reason. So you should get your host to fix the SSL configurations instead of bypassing it',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'ui' => 1,
                ),
            ),
        ),
	];
    return $data;
	// $fields['fields'] = array_merge( $fields['fields'], $data);
	// return $fields;
// },40 );

