<?php 

// add_filter( 'zadmin_acf_fields', function($fields){
	$data = [
        array(
            'key' => 'field_6415dfbdaa5f6',
            'label' => 'Woocommerce Test & Run',
            'name' => 'woocommerce_test_and_run',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_6415d5039b48e',
                    'label' => 'From Product',
                    'name' => 'from_post_copy2',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6415d5049b48f',
                            'label' => 'From post',
                            'name' => 'text',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_6415d5049b490',
                            'label' => 'Test & run',
                            'name' => 'test_and_run',
                            'aria-label' => '',
                            'type' => 'button_group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'Test' => 'Test',
                                'Run' => 'Run',
                            ),
                            'default_value' => '',
                            'return_format' => 'value',
                            'allow_null' => 0,
                            'layout' => 'horizontal',
                        ),
                        array(
                            'key' => 'field_6415d5049b491',
                            'label' => 'Message',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_6415dfbdaa603',
                    'label' => 'From Product category',
                    'name' => 'from_post_copy2',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => 'Check single import before run category import is recommended.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6415dfbdaa604',
                            'label' => 'From post',
                            'name' => 'text',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_6415dfbdaa605',
                            'label' => 'Test & run',
                            'name' => 'test_and_run',
                            'aria-label' => '',
                            'type' => 'button_group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'Test' => 'Test',
                                'Run' => 'Run',
                            ),
                            'default_value' => '',
                            'return_format' => 'value',
                            'allow_null' => 0,
                            'layout' => 'horizontal',
                        ),
                        array(
                            'key' => 'field_6415dfbdaa606',
                            'label' => 'Message',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                    ),
                ),
            ),
        ),
	];
    return $data;
	// $fields['fields'] = array_merge( $fields['fields'], $data);
	// return $fields;
// },80 );

