<?php return array(
    'key' => 'field_6414a26caaeea',
    'label' => 'Custom Code',
    'name' => 'custom_code',
    'aria-label' => '',
    'type' => 'group',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '100',
        'class' => '',
        'id' => '',
    ),
    'layout' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_6414a27aaaef4',
            'label' => 'Custom CSS',
            'name' => 'custom_css',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => 'Your custom css here will be enqueue in header...',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'text',
            'media_upload' => 0,
            'toolbar' => 'full',
            'delay' => 0,
        ),
        array(
            'key' => 'field_6414a2c884fd4',
            'label' => 'Custom Js',
            'name' => 'custom_js',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => 'Code inside script tag will be enqueue in footer...',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'text',
            'media_upload' => 0,
            'toolbar' => 'full',
            'delay' => 0,
        ),
    ),
) ?>