<?php 
return array(
    'key' => 'field_6414ad7b99b67',
    'label' => 'Wordpress Librbary',
    'name' => 'wp_library',
    'aria-label' => '',
    'type' => 'group',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '50',
        'class' => '',
        'id' => '',
    ),
    'layout' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'js_library',
            'label' => 'JS Library',
            'name' => 'js_library',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '<a target=_blank href="https://developer.wordpress.org/reference/functions/wp_enqueue_script/">Document</a>',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'choices' => zadmin_convert_fields_array(array_keys(wp_scripts()->registered)),
            'default_value' => array(
            ),
            'return_format' => 'value',
            'multiple' => 1,
            'allow_null' => 1,
            'ui' => 1,
            'ajax' => 1,
            'placeholder' => '',
        ),
        array(
            'key' => 'css_library',
            'label' => 'CSS Library',
            'name' => 'css_library',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'choices' => zadmin_convert_fields_array(array_keys(wp_styles()->registered)),
            'default_value' => array(
            ),
            'return_format' => 'value',
            'multiple' => 1,
            'allow_null' => 1,
            'ui' => 1,
            'ajax' => 1,
            'placeholder' => '',
        ),
    ),
); ?>