<?php 

//add_filter( 'zadmin_acf_fields', function($fields){
	$data = [
        array(
            'key' => 'field_6417468402c87',
            'label' => 'Portfolio',
            'name' => 'portfolio',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_6417469c02c95',
                    'label' => 'Portfolio rename',
                    'name' => 'portfolio_rename',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_641746a402c96',
                    'label' => 'Portfolio Categories rename',
                    'name' => 'portfolio_category_rename',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_641746aa02c97',
                    'label' => 'Portfolio Tags rename',
                    'name' => 'portfolio_tag_rename',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_641747026cc9b',
                    'label' => 'Sync portfolio with product',
                    'name' => 'sync_portfolio_with_product',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Tax 1' => 'Tax 1',
                        'Tax 2' => 'Tax 2',
                        'Tax 3' => 'Tax 3',
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_641747e51b21b',
                    'label' => 'Portfolio New Shortcodes',
                    'name' => 'portfolio_new_shortcode',
                    'aria-label' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<code>[adminz_flatsome_portfolio_product_list title="" columns = 2 depth = 1 depth_hover= 2 image_width=25 text_align= "left" style= "vertical" type="row"]</code></br> <code>[adminz_flatsome_product_portfolio_info title= "" show_producs_sync_portfolio= "" title_small= "Same Portfolio" columns = 2 depth = 1 depth_hover= 2 image_width=25 text_align= "left" style= "vertical" type="row"]</code></br> <code>[adminz_flatsome_portfolios_form]</code></br> <code>[adminz_flatsome_portfolios_search_result]</code></br>', 
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
            ),
        ),
	];
    return $data;
	//$fields['fields'] = array_merge( $fields['fields'], $data);
	//return $fields;
//},110 );

