<?php return array(
            'key' => 'field_64159819c85fb',
            'label' => 'Elements',
            'name' => 'message',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_64159819c85fc',
                    'label' => '',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => 'Some shortcode for pagebuilder has been supported.',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
            ),
        ); ?>