<?php 

// add_filter( 'zadmin_acf_fields', function($fields){
	$data = [
        array(
            'key' => 'field_6414abd19cac7',
            'label' => 'Fonts',
            'name' => 'fonts',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_6413718177b56',
                    'label' => 'Fonts Supported',
                    'name' => 'fonts_supported',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Lato' => 'Lato',
                        'Roboto' => 'Roboto',
                        'Tahoma' => 'Tahoma',
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'multiple' => 1,
                    'allow_null' => 1,
                    'ui' => 1,
                    'ajax' => 1,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_6413707eaba9f',
                    'label' => 'Upload your font files',
                    'name' => 'fonts_uploaded',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_64137136881c3',
                            'label' => 'Font file',
                            'name' => 'font_file',
                            'aria-label' => '',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => '',
                            'mime_types' => '.otf,.ttf,.woff,.woff2,.sfnt',
                            'parent_repeater' => 'field_6413707eaba9f',
                        ),
                        array(
                            'key' => 'field_641370c15f95b',
                            'label' => 'Font Family',
                            'name' => 'font-family',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_6413707eaba9f',
                        ),
                        array(
                            'key' => 'field_641370fa5f95c',
                            'label' => 'Font Weight',
                            'name' => 'font-weight',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_6413707eaba9f',
                        ),
                        array(
                            'key' => 'field_641370a6abaa2',
                            'label' => 'sdfasfas',
                            'name' => 'sdfasfas',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_6413707eaba9f',
                        ),
                        array(
                            'key' => 'field_641371045f95d',
                            'label' => 'Font Style',
                            'name' => 'font-style',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_6413707eaba9f',
                        ),
                        array(
                            'key' => 'field_641371115f95e',
                            'label' => 'Font Stretch',
                            'name' => 'font-stretch',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_6413707eaba9f',
                        ),
                    ),
                ),
            ),
        ),
	];
    return $data;
	// $fields['fields'] = array_merge( $fields['fields'], $data);
	// return $fields;
// },20 );

